openapi: 3.0.0
info:
  description: Auth service for Yandex Practicum
  version: 1.0.0
  title: AUTH Service

tags:
- name: Users
  description: Operations about user
- name: Roles
  description: Operations about roles

components:
  schemas:
    User:
      type: object
      properties:
        username:
          type: string
        password:
          type: string

    CreateUser:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
        email:
          type: string

    Error:
      type: object
      properties:
        error_code:
          type: string
        message:
          type: string
      required:
        - error_code
        - message

    Token:
      type: object
      properties:
        access_token:
          type: string
        refresh_token:
          type: string

    AuthEvent:
      type: object
      properties:
        uuid:
          type: string
          readOnly: true
        time:
          type: timestamp
        fingerprint:
          type: string

  responses:
    MinimlResponse:
      description: OK

    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    ImaTeapot:
      description: Code Execution Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    InternalError:
      description: Internal Server Error


paths:
  /user/signup:
    post:
      summary: Creation of a new user
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/CreateUser'
      description: User creation and getting token to access api methods
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Token'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '400':
          $ref: '#/components/responses/BadRequest'
        '418':
          $ref: '#/components/responses/ImaTeapot'
        '500':
          $ref: '#/components/responses/InternalError'


  /user/auth:
    post:
      summary: Authorization by username and password to get access and refresh tokens
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      description: User authorization, get tokens to access API methods
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Token'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '400':
          $ref: '#/components/responses/BadRequest'
        '418':
          $ref: '#/components/responses/ImaTeapot'
        '500':
          $ref: '#/components/responses/InternalError'

    patch:
      summary: Edit user login and/or password
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/CreateUser'
                - $ref: '#/components/schemas/Token'
      description: Edit user login and/or password
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Token'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '400':
          $ref: '#/components/responses/BadRequest'
        '418':
          $ref: '#/components/responses/ImaTeapot'
        '500':
          $ref: '#/components/responses/InternalError'

    put:
      summary: Get access and refresh token using refresh token
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/Token'
                - required:
                    - refresh_token
        description: User authorization, get access and refresh token using resfresh token
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Token'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '400':
          $ref: '#/components/responses/BadRequest'
        '418':
          $ref: '#/components/responses/ImaTeapot'
        '500':
          $ref: '#/components/responses/InternalError'

    delete:
      summary: Log out and destroy JWT Tokens
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/Token'
                - required:
                    - refresh_token
        description: Log out and destroy JWT tokens using resfresh token
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Token'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '400':
          $ref: '#/components/responses/BadRequest'
        '418':
          $ref: '#/components/responses/ImaTeapot'
        '500':
          $ref: '#/components/responses/InternalError'

    get:
      summary: Get user authorization history
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Token'
      description: Get user authorization history
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthEvent'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '400':
          $ref: '#/components/responses/BadRequest'
        '418':
          $ref: '#/components/responses/ImaTeapot'
        '500':
          $ref: '#/components/responses/InternalError'
